checks:
  addAllBuiltIn: true
  exclude:
  # Exceptions are all for test pods.
  - "no-read-only-root-fs"
  - "run-as-non-root"
  - "unset-cpu-requirements"
  - "unset-memory-requirements"
  - "latest-tag"
  - "required-annotation-email"
  - "required-label-owner"
  - "no-liveness-probe"
  - "default-service-account"
  - "no-readiness-probe"
  - "access-to-create-pods"
  - "access-to-secrets"
  - "use-namespace"
  - "minimum-three-replicas"
  - "no-rolling-update-strategy"
  - "non-isolated-pod"
  - "wildcard-in-rules"
  - "dnsconfig-options"
  - "no-node-affinity"
  - "dangling-service"
  # Temporary
  # - "deprecated-service-account-field"
  - "restart-policy"
  - "priority-class-name"
  - "job-ttl-seconds-after-finished"