annotations:
  io.giantswarm.application.audience: all
  io.giantswarm.application.restrictions.cluster-singleton: "true"
  io.giantswarm.application.team: shield
apiVersion: v2
appVersion: v1.17.0
dependencies:
  - name: policy-reporter
    version: 3.7.1
  - name: kyverno
    version: 3.7.0
description: 'Kyverno is a policy engine designed for Kubernetes. It can validate, mutate,

  and generate configurations using admission controls and background scans.

  Kyverno policies are Kubernetes resources and do not require learning a new

  language.

'
engine: gotpl
home: https://github.com/giantswarm/kyverno-app
icon: https://s.giantswarm.io/app-icons/kyverno/1/light.svg
keywords:
  - kubernetes
  - policy-agent
  - validating-webhook
  - admission-controller
name: kyverno
sources:
  - https://github.com/kyverno/kyverno
type: application
version: 0.24.0
